# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdf86bd3eb8a225ebf4bb0823789a7c15d79bb0582d525324f761d4bba8a73a80862ba005738f052230dfad773263b9f45cff9e93057719598ead2475fd0e880

test:
  secret_key_base: 0d70a832a78950db4de1c7f9a45ea9b24893612cfbe66d543ce22978bf3cb1daf8e00941a5a1fe9ea1632742e91ad6941cabc144b8a30a59054b77259149d175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
